# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLogin():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        self.driver.get("https://manage.sugarwish.com/")
        self.driver.set_window_size(1552, 840)
        self.driver.find_element(By.XPATH, "//span[contains(.,\'Sign In\')]").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'username\']").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'username\']").send_keys(
            "mykola_plakhotnik@pecodesoftware.com")
        self.driver.find_element(By.XPATH, "//input[@id=\'password\']").click()
        self.driver.find_element(By.XPATH, "//input[@id=\'password\']").send_keys("XOiz,NoIgQ-gjABROSfbqXd3")
        self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
        self.driver.find_element(By.XPATH, "//a[@id=\'desktopAccountDropdown\']/span/span[2]").click()
        self.driver.find_element(By.XPATH, "//a[contains(.,\'Log Out\')]").click()
        self.driver.close()

